extends:
  - mysticatea
  - mysticatea/modules
  - plugin:prettier/recommended

rules:
  mysticatea/arrow-parens: off
  prettier/prettier:
    - error
    - tabWidth: 4
      semi: false
      trailingComma: es5

overrides:
  - files: ["*.ts"]
    parser: typescript-eslint-parser
    rules:
      class-methods-use-this: off
      complexity: off
      lines-between-class-members: off
      init-declarations: off
      no-invalid-this: off
      no-loop-func: off
      no-undef: off
      no-unused-vars: off
      no-use-before-define: off
      one-var:
        - error
        - never
      require-jsdoc: off
      valid-jsdoc: off
      mysticatea/prefer-for-of: off
      prettier/prettier:
        - error
        - tabWidth: 4
          semi: false
          trailingComma: all
          parser: typescript
    settings:
      node:
        tryExtensions: [".ts"]
